# Generated by Django 5.0.3 on 2024-03-20 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=75)),
                ('last_name', models.CharField(blank=True, default='', max_length=75)),
                ('email', models.EmailField(blank=True, default='', max_length=150, unique=True)),
                ('password', models.CharField(default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pokemonName', models.CharField(default='', max_length=100)),
                ('HPpts', models.CharField(default='100000', max_length=10)),
                ('ATTACKpts', models.CharField(default='100000', max_length=10)),
                ('DEFENSEpts', models.CharField(default='100000', max_length=10)),
                ('SPEEDpts', models.CharField(default='100000', max_length=10)),
                ('SPATTACKpts', models.CharField(default='100000', max_length=10)),
                ('SPDEFENSEpts', models.CharField(default='100000', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pokemonUserCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=150)),
                ('pokemonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techexercise.pokemon')),
            ],
        ),
    ]
