# Generated by Django 5.0.3 on 2024-03-20 04:14

import techexercise.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techexercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', techexercise.models.CustomUserManager()),
            ],
        ),
    ]
