# Generated by Django 5.0.3 on 2024-03-18 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techexercise', '0004_user_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_test',
        ),
    ]
